### ISSUE TITLE
Can convert Java project to use CharSequence but not String

### ISSUE THREAD

**Issue by julianpeeters** [phunt/avro-rpc-quickstart#11]
Hi, great demo by the way.

I was trying to convert the Java project to use `String`, but can only get as far as changing `Main.java` to use `String`. I can get `Mail.java` and `Message.java` to use `CharSequence`, but I'm surprised that when everything is String I still get an error even though there are seemingly no more `Utf8`s left in the project: 
```
Caused by: org.apache.avro.AvroRuntimeException: java.lang.ClassCastException: org.apache.avro.util.Utf8 cannot be cast to java.lang.String
	at org.apache.avro.ipc.specific.SpecificRequestor.readError(SpecificRequestor.java:173)
	at org.apache.avro.ipc.Requestor$Response.getResponse(Requestor.java:554)
	at org.apache.avro.ipc.Requestor$TransceiverCallback.handleResult(Requestor.java:359)
	at org.apache.avro.ipc.Requestor$TransceiverCallback.handleResult(Requestor.java:322)
	at org.apache.avro.ipc.NettyTransceiver$NettyClientAvroHandler.messageReceived(NettyTransceiver.java:613)
```

Any ideas on how to use `String` throughout?
Thanks

**Comment by phunt** [comment]
Hm. Hard to say, did you change the mail.avpr definition as well?

**Comment by julianpeeters** [comment]
Thanks for the idea. I just now removed the avro-plugin and the mail.avpr after generating the classes in order to make sure I wasn't overwriting the files, and once again after attempting to modify them to use String the error is still there.

My current guess (likely wrong) is that `SpecificRequestor` can only handle `Utf8` (to enforce efficiency?), but after looking through the source, I don't immediately see where it's doing that.

So maybe this is a "can't fix". Thanks for the eyes tho. I'm happy closing this issue and if I run across a solution I'll share what I find.

**Comment by phunt** [comment]
Sorry. I'm no where near an Avro expert - perhaps if you asked on the Avro mailing list?

**Comment by julianpeeters** [comment]
No worries at all. Looks like [someone beat me to it](http://apache-avro.679487.n3.nabble.com/Utf8-to-String-ClassCastException-upon-deserialization-setting-properties-on-Union-schema-td4032922.html). Lots of views, but sadly no response :) 

For completeness' sake, I'll report that the asker seems to have had the same error deserializing GenericRecords, and has an [amusing example repo](https://github.com/ryonday/avroDecodingHelp) that seems to offer a solution of passing in both a reader schema and a writer schema. `SpecificResponder` however can only take a `Class` or a `Protocol`, and both result in the same error for me.

**Comment by phunt** [comment]
Lol. Thanks for the pointer. ttyl
