### ISSUE TITLE
What is the equivalent of libsnappy-dev for Mac OS X via brew?

### ISSUE THREAD

**Issue by emaillenin** [phunt/avro-rpc-quickstart#5]
http://stackoverflow.com/questions/22794807/installing-avro-in-mac-os-x

**Comment by phunt** [comment]
I got to test on a mac. Updated the README with these details. Thanks.

**Comment by ben-crowhurst** [comment]
@emaillenin linked to a working set of steps.  Replicated below to save others an extra hyperlink.

```
 brew install snappy
 cd /usr/local/lib/
 ln -s /usr/local/Cellar/snappy/1.1.1/lib/libsnappy.1.dylib
 ln -s /usr/local/Cellar/snappy/1.1.1/lib/libsnappy.a
 ln -s /usr/local/Cellar/snappy/1.1.1/lib/libsnappy.dylib
```
