### ISSUE TITLE
MVN Fresh install fail

### ISSUE THREAD

**Issue by aertoria** [phunt/avro-rpc-quickstart#6]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /mnt/GitHub/apache_avro/avro-rpc-quickstart/target/generated-sources/avro/example/proto/Mail.java:[10,7] error: duplicate class: example.proto.Mail
[ERROR] /mnt/GitHub/apache_avro/avro-rpc-quickstart/target/generated-sources/avro/example/proto/Message.java:[9,7] error: duplicate class: example.proto.Message

**Comment by phunt** [comment]
Odd. I just checked out a fresh clone and did "mvn clean install" and it was fine. Perhaps run mvn with more debug options? Or try to determine where the duplicate is coming from?
